### PR TITLE
feat: header ui in deposit screen

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
- Separated wallet state in a context
- Added header UI
 
Screenshot 2022-02-27 at 11 12 27 AM

### CODE REVIEW

**Comment by intergalacticspacehighway** [comment]
oops fixing conflicts

**Review by GarrettJMU — APPROVED** [review]
LGTM

**Review by bigint — APPROVED** [review]
LGTM 🚀

**Comment by GarrettJMU** [comment]
Looks like you have Merge conflicts @intergalacticspacehighway

**Comment by intergalacticspacehighway** [comment]
> Looks like you have Merge conflicts @intergalacticspacehighway

yeah, had conflicts due to formatting. Fixed and merged!

**Pull request merged**
